# Inserts a blank line between shell prompts
add_newline = true
continuation_prompt = '▶  '

[character]
success_symbol = "[λ](bold green)"
error_symbol = "[λ](bold red)"

[directory]
home_symbol = "🏠"
truncation_length = 2
truncation_symbol = "../"
format = "::[$path](bold #70dcfa)[$read_only]($read_only_style) "

[git_branch]
format = "on [$symbol](bold 220)[$branch](bold 220) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[nodejs]
disabled = true

[username]
disabled = false
show_always = true
format = "[$user](bold #f54281)"

[kubernetes]
symbol = "☸"
format = '[ $symbol $context( \($namespace\))]($style)'
disabled = false

[[kubernetes.contexts]]
context_pattern = "gke_.*_(?P<cluster>[\\w-]+)"
context_alias = "gke-$cluster"
style = "bold yellow"
